apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app1
  template:
    metadata:
      labels:
        app: react-app1
    spec:
      containers:
      - name: react-app1
        image: saikrish12345/react-todo-list:1
        ports:
        - containerPort: 3000
        resources:
          requests:
            ephemeral-storage: "500Mi"
          limits:
            ephemeral-storage: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: react-app-service
spec:
  selector:
    app: react-app1
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
    - name: nodeport
      protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32008  # Specify a node port if you want to use NodePort service type
  type: NodePort

